CoreLootManager/CoreLootManager

Modules/AuctionManager/AuctionManager.lua, Modules/BiddingManager/BiddingManager.lua, Modules/BiddingManager/GUI.lua, Modules/LedgerManager/LedgerManager.lua, Modules/RaidManager/GUI.lua, Modules/RaidManager/RaidManager.lua
=> Open bid system

ClassicLootManager.lua, ClassicLootManager.toc, GlobalConfigs.lua, Modules/BiddingManager/BiddingManager.lua, Modules/LedgerManager/LedgerManager.lua, Modules/Logger/Logger.lua, Modules/LootManager/LootManager.lua
=> Add support for configuration of announcement loot to guild

.luacheckrc, GlobalConfigs.lua, Modules/AuctionManager/GUI.lua, Modules/LootManager/LootManager.lua
=> Auction from corpse

Modules/ProfileManager/ProfileManager.lua
=> Fix for guild rank id after TBC patch

GlobalConfigs.lua, MinimapIcon.lua, Modules/BiddingManager/BiddingManager.lua, Modules/LootManager/GUI.lua, Modules/PointManager/GUI.lua, Modules/RaidManager/GUI.lua, Modules/RaidManager/Raid.lua, Utils.lua
=> Loot / Point / Raid removals through GUI

Modules/RosterManager/Roster.lua
Reverts ClassicLootManager/ClassicLootManager#62
=> Revert "Cleanup the PR branch"

Modules/AuctionManager/AuctionManager.lua, Modules/AuctionManager/GUI.lua, Modules/BiddingManager/BiddingManager.lua, Modules/BiddingManager/GUI.lua, Modules/LootManager/GUI.lua, Modules/PointManager/GUI.lua, Modules/RaidManager/GUI.lua, Modules/Standings/GUI.lua
Closes #61 
https://cdn.discordapp.com/attachments/813698369465745428/886653878668505160/unknown.png
=> Explicit pass

Modules/AuctionManager/GUI.lua, Modules/LootManager/GUI.lua, Modules/PointManager/GUI.lua, Modules/RaidManager/GUI.lua, Modules/Standings/GUI.lua
1. Store last selected roster in various windows
2. Add some coloring to DKP values
3. Fix auction window sorting for ML
=> Bunch of small gui fixes

Modules/LootManager/GUI.lua, Modules/PointManager/GUI.lua, Modules/RaidManager/GUI.lua
=> Fix right click handling and too long tooltips

Modules/BiddingManager/GUI.lua
=> Conditionally disable base/max buttons

Modules/AuctionManager/AuctionCommStructures.lua, Modules/AuctionManager/AuctionManager.lua, Modules/BiddingManager/GUI.lua
=> Display current standings in bidding window

README.md
Add a note to the readme about how the MIT license applies to our project.
=> add license note to readme

Debug.lua, GlobalSlashCommands.lua, Modules/ConfigManager/ConfigManager.lua, Modules/LootManager/LootManager.lua, Modules/PointManager/PointManager.lua, Modules/ProfileManager/Profile.lua, Modules/ProfileManager/ProfileManager.lua, Modules/RaidManager/GUI.lua, Modules/RaidManager/RaidManager.lua, Modules/RosterManager/Roster.lua, Modules/RosterManager/RosterManager.lua, Modules/Standings/GUI.lua
=> Alt main linking through slash command

Modules/BiddingManager/GUI.lua, Utils.lua
https://user-images.githubusercontent.com/43088589/140643632-4914becf-10f9-4c56-97df-eb4a9a7a4aa4.mp4
=> Disable display of bidding window if player cant use item

Modules/LootManager/GUI.lua
https://cdn.discordapp.com/attachments/841274229843296256/906983709406793790/unknown.png
=> Loot search

.luacheckrc, ClassicLootManager.lua, Modules/BiddingManager/GUI.lua
Fixes #159 
I do hope it works since i am not able to test it by myself (auctioneer has always data cached). Tested it with faking all the combinations of cache returns and then it works and falls back to displaying when not getting data within 0.5s.
=> Add double check for cache

Modules/AutoAwardManager/AutoAwardManager.lua, Modules/RaidManager/GUI.lua, Modules/RaidManager/RaidManager.lua, Modules/RosterManager/GUI.lua, Modules/RosterManager/Roster.lua
=> Enable and use per-raid configuration override

Modules/BiddingManager/BiddingManager.lua
=> Add configurable, opt-in auto-update

Modules/AuctionManager/AuctionManager.lua, Modules/Comms/Comms.lua, Modules/RaidManager/RaidManager.lua
=> Relaxed auction mechanisms

Modules/AuctionManager/AuctionManager.lua, Modules/AuctionManager/GUI.lua, Modules/BiddingManager/BiddingManager.lua, Modules/BiddingManager/GUI.lua, Modules/Logger/Logger.lua, Modules/RosterManager/GUI.lua, Modules/RosterManager/RosterManager.lua, Utils.lua
Passes are no longer displayed under bids.
Get additional info on hover about:
- People that passed
- People that cant use the item
- People that closed the window
- People who ignored / let the window expire / didnt receive the comms
=> Extended bidding stats

Modules/AuctionManager/GUI.lua, Modules/ProfileManager/GUI.lua, Modules/RosterManager/GUI.lua
=> Remove Color coding from sorting

Modules/RosterManager/GUI.lua
Closes #209 
Second part fixed by #205
=> Add filtering out alts

Modules/ACL/GuildInfoListener.lua, Modules/ProfileManager/GUI.lua, Modules/RosterManager/GUI.lua
=> Filter players in guild

Global/GlobalConfigs.lua, Modules/AuctionManager/AuctionManager.lua, Modules/AuctionManager/AutoAward.lua, Modules/AuctionManager/GUI.lua, Modules/BiddingManager/BiddingManager.lua, Modules/BiddingManager/GUI.lua, Modules/Changelog/GUI.lua, Modules/Database/Database.lua, Modules/LootManager/GUI.lua, Modules/LootQueueManager/GUI.lua, Modules/PointManager/GUI.lua, Modules/ProfileInfoManager/ProfileInfoManager.lua, Modules/ProfileManager/GUI.lua, Modules/ProfileManager/ProfileManager.lua, Modules/RaidManager/GUI.lua, Modules/RosterManager/GUI.lua, Modules/RosterManager/RosterManager.lua, Utils.lua
Closes #73 
Addresses partial changes to make code more reusable
=> Refactor DB calls

Modules/AuctionManager/GUI.lua
=> Make the note persistent on set

Global/GlobalSlashCommands.lua
=> Auto trade manually awarded items

Modules/RosterManager/Roster.lua, Modules/RosterManager/RosterManager.lua
=> Pass attendance config

Global/GlobalChatMessageHandlers.lua
=> Case instensitive commands

Modules/AuctionManager/GUI.lua, Modules/AutoAwardManager/AutoAwardManager.lua, Modules/RosterManager/Options.lua, Modules/RosterManager/Roster.lua
Closes #232 
(Changes require merging of #228 )
=> Taxation option

ClassicLootManager.lua, ClassicLootManager.toc, MinimapIcon.lua, Modules/AuctionHistoryManager/AuctionHistoryManager.lua, Modules/AuctionHistoryManager/GUI.lua, Modules/AuctionManager/AuctionManager.lua, Modules/LootManager/GUI.lua, Modules/LootManager/LootManager.lua, Utils.lua
=> Auction History

Modules/AuctionHistoryManager/AuctionHistoryManager.lua, Modules/AuctionManager/AuctionManager.lua
=> Bids will now be posted only when auction is successful

ClassicLootManager.toc, Locale/frFR.lua, Locale/ruRU.lua, Modules/RosterManager/GUI.lua, Modules/RosterManager/PointInfo.lua, Modules/RosterManager/Roster.lua
Adds some statistics and recent loot on hover on player
=> Add point statistics and latest loot to player info on hover

Modules/RosterManager/Roster.lua
=> Fix not storing without weekly cap

Migration.lua
=> move the dkp award outside of loop

ClassicLootManager.toc, Locale/deDE.lua, Modules/AuctionManager/GUI.lua
=> Check if guid exists

.github/workflows/l10npr.yml, .github/workflows/lintpr.yml, Modules/AutoAwardManager/AutoAwardManager.lua, Modules/AutoAwardManager/EncounterIDs.lua, Modules/LedgerManager/GUI.lua, Modules/RosterManager/LedgerEntries.lua, Modules/RosterManager/Options.lua, Modules/RosterManager/Roster.lua, Modules/RosterManager/RosterManager.lua
- All bosses supported
- Supports 10 and 25 man
- Does **not** support hardmodes
_- New heroic difficultyIds need to be confirmed when ToTC comes out_
=> WoTLK bosses support

Locale/deDE.lua
Reviewed line 1-1643 and corrected some words and sentences.
=> Corrected words and sentence structure

ClassicLootManager.toc, Modules/AuctionManager/AuctionCommStructures.lua, Modules/AuctionManager/AuctionManager.lua, Modules/AuctionManager/GUI.lua, Modules/BiddingManager/GUI.lua, Modules/ConfigManager/ConfigManager.lua, Modules/LedgerManager/GUI.lua, Modules/RaidManager/RaidManager.lua, Modules/RosterManager/LedgerEntries.lua, Modules/RosterManager/Options.lua, Modules/RosterManager/Roster.lua, Modules/RosterManager/RosterManager.lua, Utils.lua
=> Feature add tiered bids

Modules/PointManager/PointManager.lua, Modules/RaidManager/RaidManager.lua
=> Feature separate raid point bonuses

Modules/BiddingManager/GUI.lua
=> Close on bid

Modules/GUI/UnifiedGUI_Standings.lua
=> Highlight self

Global/GlobalConfigs.lua, Modules/BiddingManager/BiddingManager.lua, Modules/GUI/UnifiedGUI_History.lua
=> Toggle sounds

Modules/AutoAwardManager/AutoAwardManager.lua, Modules/RosterManager/Roster.lua
Move to #insert way and fix awarding
Fixes #325
=> Fix db order

CHANGELOG.md, Locale/deDE.lua, Locale/esES.lua, Locale/frFR.lua, Locale/ruRU.lua, Modules/AuctionManager/GUI.lua, Modules/Changelog/Changelog.lua, Modules/GUI/Filters.lua, Modules/GUI/UnifiedGUI.lua, Modules/GUI/UnifiedGUI_History.lua, Modules/GUI/UnifiedGUI_Profiles.lua, Modules/GUI/UnifiedGUI_Raids.lua, Modules/GUI/UnifiedGUI_Standings.lua, Modules/PointManager/PointManager.lua, Modules/ProfileManager/LedgerEntries.lua, Modules/ProfileManager/Profile.lua, Modules/ProfileManager/ProfileManager.lua, Modules/RosterManager/Roster.lua, README.md, Utils.lua
=> Locking profiles

ClassicLootManager.toc, Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua, Locale/deDE.lua, Locale/esES.lua, Locale/frFR.lua, Locale/ruRU.lua, Modules/AuctionHistoryManager/GUI.lua, Modules/BiddingManager/GUI.lua, Modules/GUI/UnifiedGUI_History.lua, Modules/LootQueueManager/GUI.lua, Modules/RosterManager/ItemValueCalculator.lua, Modules/RosterManager/LedgerEntries.lua, Modules/RosterManager/Options.lua, Modules/RosterManager/Roster.lua, Modules/RosterManager/RosterConfiguration.lua, Modules/RosterManager/RosterManager.lua
=> Dynamic item value

CHANGELOG.md, ClassicLootManager.toc, Locale/deDE.lua, Locale/esES.lua, Locale/frFR.lua, Locale/ruRU.lua, Modules/AuctionManager/AuctionManager.lua, Modules/AuctionManager/GUI.lua, Modules/BiddingManager/GUI.lua, Modules/Changelog/Changelog.lua
Closes #348 
Closes #354 
+ reworking of some other things
+ PR in Current for EPGP
=> Fix bidding gui multiple issues

Modules/GUI/UnifiedGUI_Standings.lua, Modules/RosterManager/Roster.lua
1) On Roster join player is awaded minGP
2) on minGP change, everyone in roster have their Gp calculated to have at leaast minGP
3) on decay it will limit the GP to not go below minGP
=> Fix mingp behavior

ClassicLootManager.toc, Locale/deDE.lua, Locale/esES.lua, Locale/frFR.lua, Locale/ruRU.lua, Modules/RosterManager/IndirectSlotMap.lua, Modules/RosterManager/ItemValueCalculator.lua, Modules/RosterManager/Roster.lua
WotLK Tier 7/8 Tokens will now reflect ilvl and slot of the item they give
=> Token proper handling

.luacheckrc, Integrations/Integrations.lua, Locale/deDE.lua, Locale/esES.lua, Locale/frFR.lua, Locale/ruRU.lua, Modules/EventManager/EventManager.lua
Waiting for RCLC release to see the final information in event.
=> RCLC integration

Locale/deDE.lua, Locale/esES.lua, Locale/frFR.lua, Locale/ruRU.lua, Modules/AuctionManager/AuctionManager.lua, Modules/BiddingManager/BiddingManager.lua, Modules/BiddingManager/GUI.lua
=> No ok on bid

ClassicLootManager.lua, Modules/GUI/UnifiedGUI_Profiles.lua, Utils.lua
1. abstract version parsing to function UTILS.ParseVersionString
2. function UTILS.LibStModifierFnVersion to compare version strings by converting the string into number
=> fix version string compare

Utils.lua
=> Fix missing class information

Integrations/Import.lua, Migration.lua, Modules/PointManager/LedgerEntries.lua, Modules/PointManager/PointManager.lua
Updated parseImportData in Import.lua to function sans dkp and with spent / points as well as track action count properly and update spent in the standings
Updated LedgerEntries.lua to function with Set command for spent points in epgp
Updated PointManager.lua to pass spent property into set command and added set spent mutator
=> Added import functionality for epgp

Locale/deDE.lua, Locale/esES.lua, Locale/frFR.lua, Locale/ruRU.lua, Locale/zhCN.lua, Locale/zhTW.lua, Modules/AuctionManager/AuctionCommStructures.lua, Modules/AuctionManager/AuctionManager.lua, Modules/BiddingManager/GUI.lua, Modules/RosterManager/Options.lua, Modules/RosterManager/RosterConfiguration.lua
=> Configurable os bid

Modules/PointManager/PointManager.lua, Modules/ProfileManager/ProfileManager.lua
=> Fix epgp alt main link

Locale/zhCN.lua, Locale/zhTW.lua
=> Locale zhCN fix

Modules/ProfileManager/ProfileManager.lua
=> Fix alt relink bug

ClassicLootManager/Locale/zhCN.lua, ClassicLootManager/Locale/zhTW.lua
Hi Lantis,
Thanks for your hard work!! I manually went through the google translation result and fix all the new locales.
=> zhCN Locale fix

ClassicLootManager/Modules/Auctioning/BiddingManager/BiddingManager.lua, ClassicLootManager/Modules/Auctioning/BiddingManager/BiddingTimerBar.lua, ClassicLootManager/Modules/Auctioning/BiddingManager/MultiGUI.lua
=> Fix multi auction bidding minor bugs

ClassicLootManager/Modules/Rosters/RosterManager/Options.lua
=> Read-only everything for non-managers

.vscode/settings.json, ClassicLootManager/Locale/deDE.lua, ClassicLootManager/Locale/esES.lua, ClassicLootManager/Locale/frFR.lua, ClassicLootManager/Locale/ruRU.lua, ClassicLootManager/Locale/zhCN.lua, ClassicLootManager/Locale/zhTW.lua, ClassicLootManager/Modules/GUI/UnifiedGUI_History.lua, ClassicLootManager/Modules/GUI/UnifiedGUI_Standings.lua, ClassicLootManager/Modules/Points/PointManager/LedgerEntries.lua, ClassicLootManager/Modules/Points/PointManager/PointHistory.lua, ClassicLootManager/Modules/Points/PointManager/PointManager.lua, ClassicLootManager/Modules/Rosters/RosterManager/Roster.lua, ClassicLootManager/Utils.lua, ClassicLootManager_Alerts/Alerts.lua
Fixes #490 
Adds Configurable decay for EP/GP
=> Configurable decay

ClassicLootManager/Locale/ruRU.lua
=> Locale Data from Cyber

ClassicLootManager/Modules/Auctioning/AutoAssign/AutoAssign.lua
=> Unify output for classic era and other builds for auto assing

ClassicLootManager_Integrations/Integrations.lua
=> Disenchant support

ClassicLootManager/Locale/deDE.lua, ClassicLootManager/Locale/esES.lua, ClassicLootManager/Locale/frFR.lua, ClassicLootManager/Locale/ruRU.lua, ClassicLootManager/Locale/zhCN.lua, ClassicLootManager/Locale/zhTW.lua, ClassicLootManager/Modules/Auctioning/Common/AuctionInfo.lua, ClassicLootManager/Modules/Rosters/RosterManager/Options.lua, ClassicLootManager/Modules/Rosters/RosterManager/RosterConfiguration.lua
=> Linear auction time multiplier

ClassicLootManager/Modules/Auctioning/AutoAssign/AutoAssign.lua, ClassicLootManager/Modules/Rosters/RosterManager/IndirectSlotMap.lua
=> Add ICC Tokens support. Ignore SM fragments.

ClassicLootManager/Modules/Auctioning/AutoAssign/AutoAssign.lua
=> Fix award from bags. Still ML to do

ClassicLootManager/Modules/Rosters/RosterManager/Options.lua
=> Extend image width for new windows

ClassicLootManager/Modules/Common/Comms/Comms.lua, ClassicLootManager/Utils.lua
Closes #517 
Cross-faction messages (whispers) sent over RAID channel encapsulated.
Kudos to github.com/evil-morfar/ for good insight on how to workaround it.
=> Workaround cross-faction issues

ClassicLootManager/Modules/GUI/Filters.lua, ClassicLootManager/Modules/GUI/UnifiedGUI_Profiles.lua, ClassicLootManager/Modules/GUI/UnifiedGUI_Standings.lua, README.md
=> Raid filter handling based on CLM raid

.vscode/tasks.json, ClassicLootManager/Locale/deDE.lua, ClassicLootManager/Locale/esES.lua, ClassicLootManager/Locale/frFR.lua, ClassicLootManager/Locale/ruRU.lua, ClassicLootManager/Locale/zhCN.lua, ClassicLootManager/Locale/zhTW.lua, ClassicLootManager/Modules/Auctioning/AuctionManager/AuctionManager.lua, ClassicLootManager/Modules/Auctioning/Common/AuctionInfo.lua, ClassicLootManager/Modules/Common/Comms/Comms.lua, ClassicLootManager/Modules/GUI/UnifiedGUI_Audit.lua, ClassicLootManager/Modules/GUI/UnifiedGUI_Profiles.lua, ClassicLootManager/Modules/Global/GlobalConfigs.lua, ClassicLootManager/Modules/Ledger/CrossGuildSyncManager/CrossGuildSyncManager.lua, ClassicLootManager/Modules/Rosters/RosterManager/Options.lua, ClassicLootManager/Utils.lua, scripts/l10n_strings.py
=> Fix v5 bugfixes part2

ClassicLootManager/Modules/Auctioning/BiddingManager/MultiGUI.lua
=> Fix closing on all bids

ClassicLootManager/Modules/Auctioning/AutoAssign/AutoAssign.lua
=> Fix cross-realm check

.luacheckrc, ClassicLootManager/Tooltips.lua, ClassicLootManager/Utils.lua
=> Always Display all epic and above non-equippable items values

.luacheckrc, .pkgmeta, ClassicLootManager/ClassicLootManager.toc, ClassicLootManager/Libs/_filelist.xml, ClassicLootManager/Locale/deDE.lua, ClassicLootManager/Locale/esES.lua, ClassicLootManager/Locale/frFR.lua, ClassicLootManager/Locale/ruRU.lua, ClassicLootManager/Locale/zhCN.lua, ClassicLootManager/Locale/zhTW.lua, ClassicLootManager/Modules/Auctioning/BiddingManager/BiddingTimerBar.lua, ClassicLootManager/Modules/Auctioning/BiddingManager/MultiGUI.lua, ClassicLootManager_Alerts/ClassicLootManager_Alerts.toc, ClassicLootManager_Integrations/ClassicLootManager_Integrations.toc, ClassicLootManager_Tracker/ClassicLootManager_Tracker.toc
=> Configurable timer bar through LibSharedMedia
